version: '3.8'

services:
  gifs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gifs-angular
    environment:
      - NODE_ENV=production
    ports:
      - "8080:80"
    restart: unless-stopped
