version: '3.8'

services:
  gifs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-80}:80"
    container_name: gifs-angular
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:80/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - gifs-network
    volumes:
      - nginx-logs:/var/log/nginx

networks:
  gifs-network:
    driver: bridge

volumes:
  nginx-logs:
    driver: local
