name: publish

on:
  push:
    branches:
      - main

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/garuda127/gif-app:${{ github.sha }} .
          docker tag ghcr.io/garuda127/gif-app:${{ github.sha }} ghcr.io/garuda127/gif-app:latest
          docker push ghcr.io/garuda127/gif-app:${{ github.sha }}
          docker push ghcr.io/garuda127/gif-app:latest
